
var OP = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(OP) {
  OP = OP || {};


null;var f;f||(f=typeof OP !== 'undefined' ? OP : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},f),p="";"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src);_scriptDir&&(p=_scriptDir);0!==p.indexOf("blob:")?p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):p="";var da=f.print||console.log.bind(console),u=f.printErr||console.warn.bind(console);Object.assign(f,ca);ca=null;var v=0,x;f.wasmBinary&&(x=f.wasmBinary);
var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&y("no native wasm support detected");var ea,fa=!1,ha="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ia(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ha)return ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}var ja,z,A,B,ka,C,D,ma,na;
function oa(){var a=ea.buffer;ja=a;f.HEAP8=z=new Int8Array(a);f.HEAP16=B=new Int16Array(a);f.HEAP32=C=new Int32Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=ka=new Uint16Array(a);f.HEAPU32=D=new Uint32Array(a);f.HEAPF32=ma=new Float32Array(a);f.HEAPF64=na=new Float64Array(a)}var pa,qa=[],ra=[],sa=[];function ta(){var a=f.preRun.shift();qa.unshift(a)}var E=0,ua=null,va=null;
function y(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";u(a);fa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function wa(){return F.startsWith("data:application/octet-stream;base64,")}var F;if(f.locateFile){if(F="openpave.wasm",!wa()){var xa=F;F=f.locateFile?f.locateFile(xa,p):p+xa}}else F=(new URL("openpave.wasm",import.meta.url)).toString();
function ya(){var a=F;try{if(a==F&&x)return new Uint8Array(x);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}function za(){return x||"function"!=typeof fetch?Promise.resolve().then(function(){return ya()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return ya()})}
var Aa={22984:()=>{f.pavedata.type=f["pavedata.type"];delete f["pavedata.type"];f.pavedata.direction=f["pavedata.direction"];delete f["pavedata.direction"];f.LEsystem.resulttype=f["LEsystem.resulttype"];delete f["LEsystem.resulttype"]}};function Ba(a){for(;0<a.length;)a.shift()(f)}var Ca=[],Da=0,Ea=0;
function Fa(a){this.ua=a;this.aa=a-24;this.La=function(b){D[this.aa+4>>2]=b};this.ra=function(){return D[this.aa+4>>2]};this.Ja=function(b){D[this.aa+8>>2]=b};this.Ka=function(){C[this.aa>>2]=0};this.va=function(b){z[this.aa+12>>0]=b?1:0};this.Da=function(){return 0!=z[this.aa+12>>0]};this.wa=function(){z[this.aa+13>>0]=0};this.Ha=function(b,c){this.sa(0);this.La(b);this.Ja(c);this.Ka();this.va(!1);this.wa()};this.Ba=function(){C[this.aa>>2]+=1};this.sa=function(b){D[this.aa+16>>2]=b};this.Ca=function(){return D[this.aa+
16>>2]};this.Ga=function(){if(Ga(this.ra()))return D[this.ua>>2];var b=this.Ca();return 0!==b?b:this.ua}}function Ha(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ia=void 0;function G(a){for(var b="";A[a];)b+=Ia[A[a++]];return b}var H={},I={},Ja={};function Ka(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function La(a,b){a=Ka(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ma(a){var b=Error,c=La(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var K=void 0;function L(a){throw new K(a);}var Na=void 0;function Oa(a){throw new Na(a);}function M(a,b,c){function d(k){k=c(k);k.length!==a.length&&Oa("Mismatched type converter count");for(var l=0;l<a.length;++l)N(a[l],k[l])}a.forEach(function(k){Ja[k]=b});var e=Array(b.length),g=[],h=0;b.forEach((k,l)=>{I.hasOwnProperty(k)?e[l]=I[k]:(g.push(k),H.hasOwnProperty(k)||(H[k]=[]),H[k].push(()=>{e[l]=I[k];++h;h===g.length&&d(e)}))});0===g.length&&d(e)}
function N(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||L('type "'+d+'" must have a positive integer typeid pointer');if(I.hasOwnProperty(a)){if(c.Ia)return;L("Cannot register type '"+d+"' twice")}I[a]=b;delete Ja[a];H.hasOwnProperty(a)&&(b=H[a],delete H[a],b.forEach(e=>e()))}function Pa(a){L(a.$.ca.ba.name+" instance already deleted")}var Qa=!1;function Ra(){}
function Sa(a){--a.count.value;0===a.count.value&&(a.da?a.ea.ka(a.da):a.ca.ba.ka(a.aa))}function Ta(a,b,c){if(b===c)return a;if(void 0===c.fa)return null;a=Ta(a,b,c.fa);return null===a?null:c.Aa(a)}var Ua={},Va=[];function Wa(){for(;Va.length;){var a=Va.pop();a.$.la=!1;a["delete"]()}}var Xa=void 0,Ya={};function Za(a,b){for(void 0===b&&L("ptr should not be undefined");a.fa;)b=a.na(b),a=a.fa;return Ya[b]}
function $a(a,b){b.ca&&b.aa||Oa("makeClassHandle requires ptr and ptrType");!!b.ea!==!!b.da&&Oa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ab(Object.create(a,{$:{value:b}}))}function ab(a){if("undefined"===typeof FinalizationRegistry)return ab=b=>b,a;Qa=new FinalizationRegistry(b=>{Sa(b.$)});ab=b=>{var c=b.$;c.da&&Qa.register(b,{$:c},b);return b};Ra=b=>{Qa.unregister(b)};return ab(a)}function O(){}
function bb(a,b,c){if(void 0===a[b].ha){var d=a[b];a[b]=function(){a[b].ha.hasOwnProperty(arguments.length)||L("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].ha+")!");return a[b].ha[arguments.length].apply(this,arguments)};a[b].ha=[];a[b].ha[d.oa]=d}}
function cb(a,b){f.hasOwnProperty(a)?(L("Cannot register public name '"+a+"' twice"),bb(f,a,a),f.hasOwnProperty(void 0)&&L("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].ha[void 0]=b):f[a]=b}function db(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.ia=c;this.ka=d;this.fa=e;this.Ea=g;this.na=h;this.Aa=k;this.Na=[]}
function eb(a,b,c){for(;b!==c;)b.na||L("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.na(a),b=b.fa;return a}function fb(a,b){if(null===b)return this.ta&&L("null is not a valid "+this.name),0;b.$||L('Cannot pass "'+gb(b)+'" as a '+this.name);b.$.aa||L("Cannot pass deleted object as a pointer of type "+this.name);return eb(b.$.aa,b.$.ca.ba,this.ba)}
function hb(a,b){if(null===b){this.ta&&L("null is not a valid "+this.name);if(this.qa){var c=this.Oa();null!==a&&a.push(this.ka,c);return c}return 0}b.$||L('Cannot pass "'+gb(b)+'" as a '+this.name);b.$.aa||L("Cannot pass deleted object as a pointer of type "+this.name);!this.pa&&b.$.ca.pa&&L("Cannot convert argument of type "+(b.$.ea?b.$.ea.name:b.$.ca.name)+" to parameter type "+this.name);c=eb(b.$.aa,b.$.ca.ba,this.ba);if(this.qa)switch(void 0===b.$.da&&L("Passing raw pointer to smart pointer is illegal"),
this.Ra){case 0:b.$.ea===this?c=b.$.da:L("Cannot convert argument of type "+(b.$.ea?b.$.ea.name:b.$.ca.name)+" to parameter type "+this.name);break;case 1:c=b.$.da;break;case 2:if(b.$.ea===this)c=b.$.da;else{var d=b.clone();c=this.Pa(c,ib(function(){d["delete"]()}));null!==a&&a.push(this.ka,c)}break;default:L("Unsupporting sharing policy")}return c}
function jb(a,b){if(null===b)return this.ta&&L("null is not a valid "+this.name),0;b.$||L('Cannot pass "'+gb(b)+'" as a '+this.name);b.$.aa||L("Cannot pass deleted object as a pointer of type "+this.name);b.$.ca.pa&&L("Cannot convert argument of type "+b.$.ca.name+" to parameter type "+this.name);return eb(b.$.aa,b.$.ca.ba,this.ba)}function kb(a){return this.fromWireType(C[a>>2])}
function P(a,b,c,d){this.name=a;this.ba=b;this.ta=c;this.pa=d;this.qa=!1;this.ka=this.Pa=this.Oa=this.ya=this.Ra=this.Ma=void 0;void 0!==b.fa?this.toWireType=hb:(this.toWireType=d?fb:jb,this.ga=null)}function lb(a,b){f.hasOwnProperty(a)||Oa("Replacing nonexistant public symbol");f[a]=b;f[a].oa=void 0}var mb=[];function Q(a){var b=mb[a];b||(a>=mb.length&&(mb.length=a+1),mb[a]=b=pa.get(a));return b}
function nb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=f["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=Q(b).apply(null,c);return d}}function R(a,b){a=G(a);var c=a.includes("j")?nb(a,b):Q(b);"function"!=typeof c&&L("unknown function pointer with signature "+a+": "+b);return c}var ob=void 0;function pb(a){a=qb(a);var b=G(a);V(a);return b}
function rb(a,b){function c(g){e[g]||I[g]||(Ja[g]?Ja[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new ob(a+": "+d.map(pb).join([", "]));}function tb(a,b){for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c}function ub(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function vb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=La(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function wb(a,b,c,d,e){var g=b.length;2>g&&L("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ga){k=!0;break}var l="void"!==b[0].name,n="",m="";for(c=0;c<g-2;++c)n+=(0!==c?", ":"")+"arg"+c,m+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Ka(a)+"("+n+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var q=k?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[L,d,e,ub,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+q+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+q+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);h&&(m="thisWired"+(0<m.length?", ":"")+m);a+=(l?"var rv = ":"")+"invoker(fn"+(0<m.length?", ":"")+m+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ga&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",n.push(g+"_dtor"),d.push(b[c].ga));l&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return vb(n).apply(null,d)}
function xb(a,b,c){a instanceof Object||L(c+' with invalid "this": '+a);a instanceof b.ba.constructor||L(c+' incompatible with "this" of type '+a.constructor.name);a.$.aa||L("cannot call emscripten binding method "+c+" on deleted object");return eb(a.$.aa,a.$.ca.ba,b.ba)}var yb=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}],ib=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=yb.length?yb.pop():W.length;W[b]={Qa:1,value:a};return b}};
function zb(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?z:A)[d])};case 1:return function(d){return this.fromWireType((c?B:ka)[d>>1])};case 2:return function(d){return this.fromWireType((c?C:D)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Ab(a){var b=I[a];void 0===b&&L("enum has unknown type "+pb(a));return b}function gb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Bb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ma[c>>2])};case 3:return function(c){return this.fromWireType(na[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Cb(a,b,c){switch(b){case 0:return c?function(d){return z[d]}:function(d){return A[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return ka[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return D[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Eb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ka[c];)++c;c<<=1;if(32<c-a&&Db)return Db.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Fb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function Gb(a){return 2*a.length}
function Hb(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ib(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}C[b>>2]=g;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}
function Jb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}for(var Kb=[],Lb=[null,[],[]],Mb=Array(256),Nb=0;256>Nb;++Nb)Mb[Nb]=String.fromCharCode(Nb);Ia=Mb;K=f.BindingError=Ma("BindingError");Na=f.InternalError=Ma("InternalError");O.prototype.isAliasOf=function(a){if(!(this instanceof O&&a instanceof O))return!1;var b=this.$.ca.ba,c=this.$.aa,d=a.$.ca.ba;for(a=a.$.aa;b.fa;)c=b.na(c),b=b.fa;for(;d.fa;)a=d.na(a),d=d.fa;return b===d&&c===a};
O.prototype.clone=function(){this.$.aa||Pa(this);if(this.$.ma)return this.$.count.value+=1,this;var a=ab,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.$;a=a(c.call(b,d,{$:{value:{count:e.count,la:e.la,ma:e.ma,aa:e.aa,ca:e.ca,da:e.da,ea:e.ea}}}));a.$.count.value+=1;a.$.la=!1;return a};O.prototype["delete"]=function(){this.$.aa||Pa(this);this.$.la&&!this.$.ma&&L("Object already scheduled for deletion");Ra(this);Sa(this.$);this.$.ma||(this.$.da=void 0,this.$.aa=void 0)};
O.prototype.isDeleted=function(){return!this.$.aa};O.prototype.deleteLater=function(){this.$.aa||Pa(this);this.$.la&&!this.$.ma&&L("Object already scheduled for deletion");Va.push(this);1===Va.length&&Xa&&Xa(Wa);this.$.la=!0;return this};f.getInheritedInstanceCount=function(){return Object.keys(Ya).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in Ya)Ya.hasOwnProperty(b)&&a.push(Ya[b]);return a};f.flushPendingDeletes=Wa;f.setDelayFunction=function(a){Xa=a;Va.length&&Xa&&Xa(Wa)};
P.prototype.Fa=function(a){this.ya&&(a=this.ya(a));return a};P.prototype.xa=function(a){this.ka&&this.ka(a)};P.prototype.argPackAdvance=8;P.prototype.readValueFromPointer=kb;P.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
P.prototype.fromWireType=function(a){function b(){return this.qa?$a(this.ba.ia,{ca:this.Ma,aa:c,ea:this,da:a}):$a(this.ba.ia,{ca:this,aa:a})}var c=this.Fa(a);if(!c)return this.xa(a),null;var d=Za(this.ba,c);if(void 0!==d){if(0===d.$.count.value)return d.$.aa=c,d.$.da=a,d.clone();d=d.clone();this.xa(a);return d}d=this.ba.Ea(c);d=Ua[d];if(!d)return b.call(this);d=this.pa?d.za:d.pointerType;var e=Ta(c,this.ba,d.ba);return null===e?b.call(this):this.qa?$a(d.ba.ia,{ca:d,aa:e,ea:this,da:a}):$a(d.ba.ia,
{ca:d,aa:e})};ob=f.UnboundTypeError=Ma("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};
var Xb={y:function(a,b,c,d){y("Assertion failed: "+(a?ia(A,a):"")+", at: "+[b?b?ia(A,b):"":"unknown filename",c,d?d?ia(A,d):"":"unknown function"])},a:function(a){return Ob(a+24)+24},E:function(a){a=new Fa(a);a.Da()||(a.va(!0),Da--);a.wa();Ca.push(a);a.Ba();return a.Ga()},h:function(){var a=Ea;if(!a)return v=0;var b=new Fa(a);b.sa(a);var c=b.ra();if(!c)return v=0,a;for(var d=Array.prototype.slice.call(arguments),e=0;e<d.length;e++){var g=d[e];if(0===g||g===c)break;if(Pb(g,c,b.aa+16))return v=g,a}v=
c;return a},r:function(){var a=Ea;if(!a)return v=0;var b=new Fa(a);b.sa(a);var c=b.ra();if(!c)return v=0,a;for(var d=Array.prototype.slice.call(arguments),e=0;e<d.length;e++){var g=d[e];if(0===g||g===c)break;if(Pb(g,c,b.aa+16))return v=g,a}v=c;return a},l:function(a){return V((new Fa(a)).aa)},e:function(a,b,c){(new Fa(a)).Ha(b,c);Ea=a;Da++;throw a;},k:function(a){Ea||(Ea=a);throw a;},B:function(){},J:function(a,b,c,d,e){var g=Ha(c);b=G(b);N(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,
k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var k=z;else if(2===c)k=B;else if(4===c)k=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[h>>g])},ga:null})},o:function(a,b,c,d,e,g,h,k,l,n,m,q,r){m=G(m);g=R(e,g);k&&(k=R(h,k));n&&(n=R(l,n));r=R(q,r);var w=Ka(m);cb(w,function(){rb("Cannot construct "+m+" due to unbound types",[d])});M([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var S=t.ba;var T=S.ia}else T=O.prototype;t=La(w,function(){if(Object.getPrototypeOf(this)!==
U)throw new K("Use 'new' to construct "+m);if(void 0===J.ja)throw new K(m+" has no accessible constructor");var sb=J.ja[arguments.length];if(void 0===sb)throw new K("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.ja).toString()+") parameters instead!");return sb.apply(this,arguments)});var U=Object.create(T,{constructor:{value:t}});t.prototype=U;var J=new db(m,t,U,r,S,g,k,n);S=new P(m,J,!0,!1);T=new P(m+"*",J,!1,!1);var la=new P(m+
" const*",J,!1,!0);Ua[a]={pointerType:T,za:la};lb(w,t);return[S,T,la]})},m:function(a,b,c,d,e,g){0<b||y();var h=tb(b,c);e=R(d,e);M([],[a],function(k){k=k[0];var l="constructor "+k.name;void 0===k.ba.ja&&(k.ba.ja=[]);if(void 0!==k.ba.ja[b-1])throw new K("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");k.ba.ja[b-1]=()=>{rb("Cannot construct "+
k.name+" due to unbound types",h)};M([],h,function(n){n.splice(1,0,null);k.ba.ja[b-1]=wb(l,n,null,e,g);return[]});return[]})},b:function(a,b,c,d,e,g,h,k){var l=tb(c,d);b=G(b);g=R(e,g);M([],[a],function(n){function m(){rb("Cannot call "+q+" due to unbound types",l)}n=n[0];var q=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.ba.Na.push(b);var r=n.ba.ia,w=r[b];void 0===w||void 0===w.ha&&w.className!==n.name&&w.oa===c-2?(m.oa=c-2,m.className=n.name,r[b]=m):(bb(r,b,q),r[b].ha[c-2]=m);
M([],l,function(t){t=wb(q,t,n,g,h);void 0===r[b].ha?(t.oa=c-2,r[b]=t):r[b].ha[c-2]=t;return[]});return[]})},i:function(a,b,c,d,e,g,h,k,l,n){b=G(b);e=R(d,e);M([],[a],function(m){m=m[0];var q=m.name+"."+b,r={get:function(){rb("Cannot access "+q+" due to unbound types",[c,h])},enumerable:!0,configurable:!0};r.set=l?()=>{rb("Cannot access "+q+" due to unbound types",[c,h])}:()=>{L(q+" is a read-only property")};Object.defineProperty(m.ba.ia,b,r);M([],l?[c,h]:[c],function(w){var t=w[0],S={get:function(){var U=
xb(this,m,q+" getter");return t.fromWireType(e(g,U))},enumerable:!0};if(l){l=R(k,l);var T=w[1];S.set=function(U){var J=xb(this,m,q+" setter"),la=[];l(n,J,T.toWireType(la,U));ub(la)}}Object.defineProperty(m.ba.ia,b,S);return[]});return[]})},I:function(a,b){b=G(b);N(a,{name:b,fromWireType:function(c){c||L("Cannot use deleted val. handle = "+c);var d=W[c].value;4<c&&0===--W[c].Qa&&(W[c]=void 0,yb.push(c));return d},toWireType:function(c,d){return ib(d)},argPackAdvance:8,readValueFromPointer:kb,ga:null})},
s:function(a,b,c,d){function e(){}c=Ha(c);b=G(b);e.values={};N(a,{name:b,constructor:e,fromWireType:function(g){return this.constructor.values[g]},toWireType:function(g,h){return h.value},argPackAdvance:8,readValueFromPointer:zb(b,c,d),ga:null});cb(b,e)},c:function(a,b,c){var d=Ab(a);b=G(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:La(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},x:function(a,b,c){c=Ha(c);b=G(b);N(a,{name:b,fromWireType:function(d){return d},
toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Bb(b,c),ga:null})},n:function(a,b,c,d,e){b=G(b);-1===e&&(e=4294967295);e=Ha(c);var g=k=>k;if(0===d){var h=32-8*c;g=k=>k<<h>>>h}c=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};N(a,{name:b,fromWireType:g,toWireType:c,argPackAdvance:8,readValueFromPointer:Cb(b,e,0!==d),ga:null})},j:function(a,b,c){function d(g){g>>=2;var h=D;return new e(ja,h[g+1],h[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,
Int32Array,Uint32Array,Float32Array,Float64Array][b];c=G(c);N(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Ia:!0})},w:function(a,b){b=G(b);var c="std::string"===b;N(a,{name:b,fromWireType:function(d){var e=D[d>>2],g=d+4;if(c)for(var h=g,k=0;k<=e;++k){var l=g+k;if(k==e||0==A[l]){h=h?ia(A,h,l-h):"";if(void 0===n)var n=h;else n+=String.fromCharCode(0),n+=h;h=l+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(A[g+k]);n=n.join("")}V(d);return n},toWireType:function(d,e){e instanceof
ArrayBuffer&&(e=new Uint8Array(e));var g,h="string"==typeof e;h||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||L("Cannot pass non-string to std::string");var k;if(c&&h)for(g=k=0;g<e.length;++g){var l=e.charCodeAt(g);127>=l?k++:2047>=l?k+=2:55296<=l&&57343>=l?(k+=4,++g):k+=3}else k=e.length;g=k;k=Ob(4+g+1);l=k+4;D[k>>2]=g;if(c&&h){if(h=l,l=g+1,g=A,0<l){l=h+l-1;for(var n=0;n<e.length;++n){var m=e.charCodeAt(n);if(55296<=m&&57343>=m){var q=e.charCodeAt(++n);m=65536+
((m&1023)<<10)|q&1023}if(127>=m){if(h>=l)break;g[h++]=m}else{if(2047>=m){if(h+1>=l)break;g[h++]=192|m>>6}else{if(65535>=m){if(h+2>=l)break;g[h++]=224|m>>12}else{if(h+3>=l)break;g[h++]=240|m>>18;g[h++]=128|m>>12&63}g[h++]=128|m>>6&63}g[h++]=128|m&63}}g[h]=0}}else if(h)for(h=0;h<g;++h)n=e.charCodeAt(h),255<n&&(V(l),L("String has UTF-16 code units that do not fit in 8 bits")),A[l+h]=n;else for(h=0;h<g;++h)A[l+h]=e[h];null!==d&&d.push(V,k);return k},argPackAdvance:8,readValueFromPointer:kb,ga:function(d){V(d)}})},
t:function(a,b,c){c=G(c);if(2===b){var d=Eb;var e=Fb;var g=Gb;var h=()=>ka;var k=1}else 4===b&&(d=Hb,e=Ib,g=Jb,h=()=>D,k=2);N(a,{name:c,fromWireType:function(l){for(var n=D[l>>2],m=h(),q,r=l+4,w=0;w<=n;++w){var t=l+4+w*b;if(w==n||0==m[t>>k])r=d(r,t-r),void 0===q?q=r:(q+=String.fromCharCode(0),q+=r),r=t+b}V(l);return q},toWireType:function(l,n){"string"!=typeof n&&L("Cannot pass non-string to C++ string type "+c);var m=g(n),q=Ob(4+m+b);D[q>>2]=m>>k;e(n,q+4,m+b);null!==l&&l.push(V,q);return q},argPackAdvance:8,
readValueFromPointer:kb,ga:function(l){V(l)}})},K:function(a,b){b=G(b);N(a,{Sa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},u:function(){y("")},z:function(a,b,c){Kb.length=0;var d;for(c>>=2;d=A[b++];)c+=105!=d&c,Kb.push(105==d?C[c]:na[c++>>1]),++c;return Aa[a].apply(null,Kb)},H:function(a,b,c){A.copyWithin(a,b,b+c)},F:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,
d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{ea.grow(e-ja.byteLength+65535>>>16);oa();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},G:function(){return 52},A:function(){return 70},v:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var h=D[b>>2],k=D[b+4>>2];b+=8;for(var l=0;l<k;l++){var n=A[h+l],m=Lb[a];0===n||10===n?((1===a?da:u)(ia(m,0)),m.length=0):m.push(n)}e+=k}D[d>>2]=e;return 0},d:function(){return v},g:Qb,M:Rb,D:Sb,p:Tb,q:Ub,f:Vb,L:Wb,C:function(a){v=a}};
(function(){function a(e){f.asm=e.exports;ea=f.asm.N;oa();pa=f.asm.Q;ra.unshift(f.asm.O);E--;f.monitorRunDependencies&&f.monitorRunDependencies(E);0==E&&(null!==ua&&(clearInterval(ua),ua=null),va&&(e=va,va=null,e()))}function b(e){a(e.instance)}function c(e){return za().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){u("failed to asynchronously prepare wasm: "+g);y(g)})}var d={a:Xb};E++;f.monitorRunDependencies&&f.monitorRunDependencies(E);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return u("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return x||"function"!=typeof WebAssembly.instantiateStreaming||wa()||"function"!=typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){u("wasm streaming compile failed: "+g);u("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.O).apply(null,arguments)};var V=f._free=function(){return(V=f._free=f.asm.P).apply(null,arguments)},Ob=f._malloc=function(){return(Ob=f._malloc=f.asm.R).apply(null,arguments)},qb=f.___getTypeName=function(){return(qb=f.___getTypeName=f.asm.S).apply(null,arguments)};f.__embind_initialize_bindings=function(){return(f.__embind_initialize_bindings=f.asm.T).apply(null,arguments)};
var X=f._setThrew=function(){return(X=f._setThrew=f.asm.U).apply(null,arguments)},Y=f.stackSave=function(){return(Y=f.stackSave=f.asm.V).apply(null,arguments)},Z=f.stackRestore=function(){return(Z=f.stackRestore=f.asm.W).apply(null,arguments)},Pb=f.___cxa_can_catch=function(){return(Pb=f.___cxa_can_catch=f.asm.X).apply(null,arguments)},Ga=f.___cxa_is_pointer_type=function(){return(Ga=f.___cxa_is_pointer_type=f.asm.Y).apply(null,arguments)};
f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.Z).apply(null,arguments)};function Qb(a,b,c){var d=Y();try{return Q(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Rb(a,b,c,d,e){var g=Y();try{return Q(a)(b,c,d,e)}catch(h){Z(g);if(h!==h+0)throw h;X(1,0)}}function Vb(a,b,c,d){var e=Y();try{Q(a)(b,c,d)}catch(g){Z(e);if(g!==g+0)throw g;X(1,0)}}function Tb(a,b){var c=Y();try{Q(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;X(1,0)}}
function Wb(a,b,c,d,e){var g=Y();try{Q(a)(b,c,d,e)}catch(h){Z(g);if(h!==h+0)throw h;X(1,0)}}function Ub(a,b,c){var d=Y();try{Q(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;X(1,0)}}function Sb(a){var b=Y();try{Q(a)()}catch(c){Z(b);if(c!==c+0)throw c;X(1,0)}}var Yb;va=function Zb(){Yb||$b();Yb||(va=Zb)};
function $b(){function a(){if(!Yb&&(Yb=!0,f.calledRun=!0,!fa)){Ba(ra);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();sa.unshift(b)}Ba(sa)}}if(!(0<E)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ta();Ba(qa);0<E||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();$b();


  return OP.ready
}
);
})();
export default OP;